on: [push]

jobs:
  billing_job:
    runs-on: ubuntu-latest
    name: Run the ABE billing prototype
    steps:
      - uses: actions/checkout@v3
      - name: Do billing
        id: hello-billing
        uses: drym-org/abe-prototype@v1
